// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ai_service.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 获取Ai 误报/漏报 配置请求
type ShowReq struct {
	Appid                uint64   `protobuf:"varint,1,opt,name=Appid,proto3" json:"Appid,omitempty"`
	Where                string   `protobuf:"bytes,2,opt,name=Where,proto3" json:"Where,omitempty"`
	OrderBy              string   `protobuf:"bytes,3,opt,name=OrderBy,proto3" json:"OrderBy,omitempty"`
	Page                 int64    `protobuf:"varint,4,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize             int64    `protobuf:"varint,5,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowReq) Reset()         { *m = ShowReq{} }
func (m *ShowReq) String() string { return proto.CompactTextString(m) }
func (*ShowReq) ProtoMessage()    {}
func (*ShowReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_013b69ef8a999b36, []int{0}
}

func (m *ShowReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowReq.Unmarshal(m, b)
}
func (m *ShowReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowReq.Marshal(b, m, deterministic)
}
func (m *ShowReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowReq.Merge(m, src)
}
func (m *ShowReq) XXX_Size() int {
	return xxx_messageInfo_ShowReq.Size(m)
}
func (m *ShowReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowReq.DiscardUnknown(m)
}

var xxx_messageInfo_ShowReq proto.InternalMessageInfo

func (m *ShowReq) GetAppid() uint64 {
	if m != nil {
		return m.Appid
	}
	return 0
}

func (m *ShowReq) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

func (m *ShowReq) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

func (m *ShowReq) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ShowReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// 添加Ai误报信息
type AddAiDistortReq struct {
	Appid                uint64   `protobuf:"varint,1,opt,name=Appid,proto3" json:"Appid,omitempty"`
	Domain               string   `protobuf:"bytes,2,opt,name=Domain,proto3" json:"Domain,omitempty"`
	Payload              string   `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	From                 string   `protobuf:"bytes,4,opt,name=From,proto3" json:"From,omitempty"`
	Remark               string   `protobuf:"bytes,5,opt,name=Remark,proto3" json:"Remark,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAiDistortReq) Reset()         { *m = AddAiDistortReq{} }
func (m *AddAiDistortReq) String() string { return proto.CompactTextString(m) }
func (*AddAiDistortReq) ProtoMessage()    {}
func (*AddAiDistortReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_013b69ef8a999b36, []int{1}
}

func (m *AddAiDistortReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAiDistortReq.Unmarshal(m, b)
}
func (m *AddAiDistortReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAiDistortReq.Marshal(b, m, deterministic)
}
func (m *AddAiDistortReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAiDistortReq.Merge(m, src)
}
func (m *AddAiDistortReq) XXX_Size() int {
	return xxx_messageInfo_AddAiDistortReq.Size(m)
}
func (m *AddAiDistortReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAiDistortReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddAiDistortReq proto.InternalMessageInfo

func (m *AddAiDistortReq) GetAppid() uint64 {
	if m != nil {
		return m.Appid
	}
	return 0
}

func (m *AddAiDistortReq) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AddAiDistortReq) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *AddAiDistortReq) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *AddAiDistortReq) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

//// 删除Ai误报信息
type DeleteAiDistortReq struct {
	Uin                  uint64   `protobuf:"varint,1,opt,name=Uin,proto3" json:"Uin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAiDistortReq) Reset()         { *m = DeleteAiDistortReq{} }
func (m *DeleteAiDistortReq) String() string { return proto.CompactTextString(m) }
func (*DeleteAiDistortReq) ProtoMessage()    {}
func (*DeleteAiDistortReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_013b69ef8a999b36, []int{2}
}

func (m *DeleteAiDistortReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAiDistortReq.Unmarshal(m, b)
}
func (m *DeleteAiDistortReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAiDistortReq.Marshal(b, m, deterministic)
}
func (m *DeleteAiDistortReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAiDistortReq.Merge(m, src)
}
func (m *DeleteAiDistortReq) XXX_Size() int {
	return xxx_messageInfo_DeleteAiDistortReq.Size(m)
}
func (m *DeleteAiDistortReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAiDistortReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAiDistortReq proto.InternalMessageInfo

func (m *DeleteAiDistortReq) GetUin() uint64 {
	if m != nil {
		return m.Uin
	}
	return 0
}

// 成功与否
type Ack struct {
	IsOk                 bool     `protobuf:"varint,1,opt,name=IsOk,proto3" json:"IsOk,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ack) Reset()         { *m = Ack{} }
func (m *Ack) String() string { return proto.CompactTextString(m) }
func (*Ack) ProtoMessage()    {}
func (*Ack) Descriptor() ([]byte, []int) {
	return fileDescriptor_013b69ef8a999b36, []int{3}
}

func (m *Ack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ack.Unmarshal(m, b)
}
func (m *Ack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ack.Marshal(b, m, deterministic)
}
func (m *Ack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ack.Merge(m, src)
}
func (m *Ack) XXX_Size() int {
	return xxx_messageInfo_Ack.Size(m)
}
func (m *Ack) XXX_DiscardUnknown() {
	xxx_messageInfo_Ack.DiscardUnknown(m)
}

var xxx_messageInfo_Ack proto.InternalMessageInfo

func (m *Ack) GetIsOk() bool {
	if m != nil {
		return m.IsOk
	}
	return false
}

// 页码结构体
type PaginationRsp struct {
	Page                 int64    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=PageSize,proto3" json:"PageSize,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=Total,proto3" json:"Total,omitempty"`
	TotalPage            int64    `protobuf:"varint,4,opt,name=TotalPage,proto3" json:"TotalPage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaginationRsp) Reset()         { *m = PaginationRsp{} }
func (m *PaginationRsp) String() string { return proto.CompactTextString(m) }
func (*PaginationRsp) ProtoMessage()    {}
func (*PaginationRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_013b69ef8a999b36, []int{4}
}

func (m *PaginationRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationRsp.Unmarshal(m, b)
}
func (m *PaginationRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationRsp.Marshal(b, m, deterministic)
}
func (m *PaginationRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationRsp.Merge(m, src)
}
func (m *PaginationRsp) XXX_Size() int {
	return xxx_messageInfo_PaginationRsp.Size(m)
}
func (m *PaginationRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationRsp proto.InternalMessageInfo

func (m *PaginationRsp) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PaginationRsp) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *PaginationRsp) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PaginationRsp) GetTotalPage() int64 {
	if m != nil {
		return m.TotalPage
	}
	return 0
}

//Ai误报信息
type AiDistortRsp struct {
	Uin                  uint64   `protobuf:"varint,1,opt,name=Uin,proto3" json:"Uin,omitempty"`
	Appid                uint64   `protobuf:"varint,2,opt,name=Appid,proto3" json:"Appid,omitempty"`
	Domain               string   `protobuf:"bytes,3,opt,name=Domain,proto3" json:"Domain,omitempty"`
	Payload              string   `protobuf:"bytes,4,opt,name=Payload,proto3" json:"Payload,omitempty"`
	From                 string   `protobuf:"bytes,5,opt,name=From,proto3" json:"From,omitempty"`
	Remark               string   `protobuf:"bytes,6,opt,name=Remark,proto3" json:"Remark,omitempty"`
	Status               uint32   `protobuf:"varint,7,opt,name=Status,proto3" json:"Status,omitempty"`
	CreatedAt            int64    `protobuf:"varint,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AiDistortRsp) Reset()         { *m = AiDistortRsp{} }
func (m *AiDistortRsp) String() string { return proto.CompactTextString(m) }
func (*AiDistortRsp) ProtoMessage()    {}
func (*AiDistortRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_013b69ef8a999b36, []int{5}
}

func (m *AiDistortRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AiDistortRsp.Unmarshal(m, b)
}
func (m *AiDistortRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AiDistortRsp.Marshal(b, m, deterministic)
}
func (m *AiDistortRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AiDistortRsp.Merge(m, src)
}
func (m *AiDistortRsp) XXX_Size() int {
	return xxx_messageInfo_AiDistortRsp.Size(m)
}
func (m *AiDistortRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_AiDistortRsp.DiscardUnknown(m)
}

var xxx_messageInfo_AiDistortRsp proto.InternalMessageInfo

func (m *AiDistortRsp) GetUin() uint64 {
	if m != nil {
		return m.Uin
	}
	return 0
}

func (m *AiDistortRsp) GetAppid() uint64 {
	if m != nil {
		return m.Appid
	}
	return 0
}

func (m *AiDistortRsp) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *AiDistortRsp) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *AiDistortRsp) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *AiDistortRsp) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *AiDistortRsp) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AiDistortRsp) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

//获取Ai误报信息响应
type ShowAiDistortRsp struct {
	AiDistorts           []*AiDistortRsp `protobuf:"bytes,1,rep,name=AiDistorts,proto3" json:"AiDistorts,omitempty"`
	Pagination           *PaginationRsp  `protobuf:"bytes,2,opt,name=Pagination,proto3" json:"Pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ShowAiDistortRsp) Reset()         { *m = ShowAiDistortRsp{} }
func (m *ShowAiDistortRsp) String() string { return proto.CompactTextString(m) }
func (*ShowAiDistortRsp) ProtoMessage()    {}
func (*ShowAiDistortRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_013b69ef8a999b36, []int{6}
}

func (m *ShowAiDistortRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowAiDistortRsp.Unmarshal(m, b)
}
func (m *ShowAiDistortRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowAiDistortRsp.Marshal(b, m, deterministic)
}
func (m *ShowAiDistortRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowAiDistortRsp.Merge(m, src)
}
func (m *ShowAiDistortRsp) XXX_Size() int {
	return xxx_messageInfo_ShowAiDistortRsp.Size(m)
}
func (m *ShowAiDistortRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowAiDistortRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ShowAiDistortRsp proto.InternalMessageInfo

func (m *ShowAiDistortRsp) GetAiDistorts() []*AiDistortRsp {
	if m != nil {
		return m.AiDistorts
	}
	return nil
}

func (m *ShowAiDistortRsp) GetPagination() *PaginationRsp {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*ShowReq)(nil), "pb.ShowReq")
	proto.RegisterType((*AddAiDistortReq)(nil), "pb.AddAiDistortReq")
	proto.RegisterType((*DeleteAiDistortReq)(nil), "pb.DeleteAiDistortReq")
	proto.RegisterType((*Ack)(nil), "pb.Ack")
	proto.RegisterType((*PaginationRsp)(nil), "pb.PaginationRsp")
	proto.RegisterType((*AiDistortRsp)(nil), "pb.AiDistortRsp")
	proto.RegisterType((*ShowAiDistortRsp)(nil), "pb.ShowAiDistortRsp")
}

func init() { proto.RegisterFile("ai_service.proto", fileDescriptor_013b69ef8a999b36) }

var fileDescriptor_013b69ef8a999b36 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xcb, 0x8e, 0xd3, 0x30,
	0x14, 0x1d, 0x27, 0x7d, 0xde, 0x4e, 0x35, 0xc5, 0x8c, 0x46, 0xa6, 0x62, 0x11, 0x79, 0x81, 0xb2,
	0xaa, 0xa0, 0xcc, 0x0f, 0x04, 0x2a, 0x24, 0x56, 0x53, 0xb9, 0x20, 0x96, 0xc8, 0x6d, 0xac, 0x19,
	0xab, 0x0f, 0x07, 0xdb, 0x30, 0x1a, 0x36, 0xac, 0xf8, 0x0f, 0xbe, 0x87, 0xaf, 0x42, 0x76, 0xd3,
	0xc4, 0xa1, 0xed, 0x2a, 0xf7, 0x9c, 0xf8, 0xda, 0xe7, 0x1c, 0x5f, 0xc3, 0x88, 0xcb, 0xaf, 0x46,
	0xe8, 0x1f, 0x72, 0x25, 0x26, 0x85, 0x56, 0x56, 0xe1, 0xa8, 0x58, 0xd2, 0x5f, 0xd0, 0x5d, 0x3c,
	0xa8, 0x47, 0x26, 0xbe, 0xe1, 0x6b, 0x68, 0x67, 0x45, 0x21, 0x73, 0x82, 0x12, 0x94, 0xb6, 0xd8,
	0x1e, 0x38, 0xf6, 0xcb, 0x83, 0xd0, 0x82, 0x44, 0x09, 0x4a, 0xfb, 0x6c, 0x0f, 0x30, 0x81, 0xee,
	0x9d, 0xce, 0x85, 0x7e, 0xf7, 0x44, 0x62, 0xcf, 0x1f, 0x20, 0xc6, 0xd0, 0x9a, 0xf3, 0x7b, 0x41,
	0x5a, 0x09, 0x4a, 0x63, 0xe6, 0x6b, 0x3c, 0x86, 0x9e, 0xfb, 0x2e, 0xe4, 0x4f, 0x41, 0xda, 0x9e,
	0xaf, 0x30, 0xfd, 0x8d, 0xe0, 0x2a, 0xcb, 0xf3, 0x4c, 0xce, 0xa4, 0xb1, 0x4a, 0xdb, 0xf3, 0x4a,
	0x6e, 0xa0, 0x33, 0x53, 0x5b, 0x2e, 0x77, 0xa5, 0x94, 0x12, 0x39, 0x2d, 0x73, 0xfe, 0xb4, 0x51,
	0x3c, 0x3f, 0x68, 0x29, 0xa1, 0xd3, 0xf2, 0x41, 0xab, 0xad, 0xd7, 0xd2, 0x67, 0xbe, 0x76, 0xbb,
	0x30, 0xb1, 0xe5, 0x7a, 0xed, 0x95, 0xf4, 0x59, 0x89, 0xe8, 0x2b, 0xc0, 0x33, 0xb1, 0x11, 0x56,
	0x34, 0x94, 0x8c, 0x20, 0xfe, 0x2c, 0x77, 0xa5, 0x0e, 0x57, 0xd2, 0x17, 0x10, 0x67, 0xab, 0xb5,
	0xdb, 0xfa, 0xa3, 0xb9, 0x5b, 0xfb, 0x3f, 0x3d, 0xe6, 0x6b, 0x6a, 0x60, 0x38, 0xe7, 0xf7, 0x72,
	0xc7, 0xad, 0x54, 0x3b, 0x66, 0x8a, 0x2a, 0x0b, 0x74, 0x26, 0x8b, 0xa8, 0x99, 0x85, 0xf3, 0xfd,
	0x49, 0x59, 0xbe, 0xf1, 0x3e, 0x62, 0xb6, 0x07, 0xf8, 0x25, 0xf4, 0x7d, 0x11, 0xc4, 0x5a, 0x13,
	0xf4, 0x2f, 0x82, 0xcb, 0x5a, 0xb2, 0x29, 0x8e, 0x25, 0xd7, 0x71, 0x46, 0xa7, 0xe3, 0x8c, 0xcf,
	0xc5, 0xd9, 0x3a, 0x1d, 0x67, 0xfb, 0x64, 0x9c, 0x9d, 0x30, 0x4e, 0xc7, 0x2f, 0x2c, 0xb7, 0xdf,
	0x0d, 0xe9, 0x26, 0x28, 0x1d, 0xb2, 0x12, 0x39, 0x33, 0xef, 0xb5, 0xe0, 0x56, 0xe4, 0x99, 0x25,
	0xbd, 0xbd, 0x99, 0x8a, 0xa0, 0x8f, 0x30, 0x72, 0xd3, 0xd8, 0xf0, 0xf3, 0x1a, 0xa0, 0xc2, 0x86,
	0xa0, 0x24, 0x4e, 0x07, 0xd3, 0xd1, 0xa4, 0x58, 0x4e, 0xc2, 0x55, 0x2c, 0x58, 0x83, 0xdf, 0x00,
	0xd4, 0xf7, 0xe0, 0x4d, 0x0f, 0xa6, 0xcf, 0x5c, 0x47, 0xe3, 0x76, 0x58, 0xb0, 0x68, 0xfa, 0x07,
	0x41, 0x94, 0x49, 0x7c, 0x0b, 0xc3, 0xc6, 0xf9, 0x78, 0xe0, 0xda, 0xca, 0x07, 0x32, 0xbe, 0x3e,
	0x80, 0xf0, 0x64, 0x7a, 0x81, 0x27, 0x70, 0x19, 0x4e, 0x30, 0x7e, 0xee, 0xd5, 0x35, 0x67, 0x7a,
	0xdc, 0xf5, 0xe4, 0x6a, 0x4d, 0x2f, 0xf0, 0x2d, 0x5c, 0xfd, 0x37, 0x6a, 0xf8, 0xc6, 0xfd, 0x3d,
	0x9e, 0xbf, 0xa0, 0x6b, 0xd9, 0xf1, 0x8f, 0xf6, 0xed, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8b,
	0xb2, 0x19, 0x96, 0xc8, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AiClient is the client API for Ai service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AiClient interface {
	ShowAiDistort(ctx context.Context, in *ShowReq, opts ...grpc.CallOption) (*ShowAiDistortRsp, error)
	AddAiDistort(ctx context.Context, in *AddAiDistortReq, opts ...grpc.CallOption) (*Ack, error)
	DeleteAiDistort(ctx context.Context, in *DeleteAiDistortReq, opts ...grpc.CallOption) (*Ack, error)
}

type aiClient struct {
	cc *grpc.ClientConn
}

func NewAiClient(cc *grpc.ClientConn) AiClient {
	return &aiClient{cc}
}

func (c *aiClient) ShowAiDistort(ctx context.Context, in *ShowReq, opts ...grpc.CallOption) (*ShowAiDistortRsp, error) {
	out := new(ShowAiDistortRsp)
	err := c.cc.Invoke(ctx, "/pb.Ai/ShowAiDistort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) AddAiDistort(ctx context.Context, in *AddAiDistortReq, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/pb.Ai/AddAiDistort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) DeleteAiDistort(ctx context.Context, in *DeleteAiDistortReq, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/pb.Ai/DeleteAiDistort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiServer is the server API for Ai service.
type AiServer interface {
	ShowAiDistort(context.Context, *ShowReq) (*ShowAiDistortRsp, error)
	AddAiDistort(context.Context, *AddAiDistortReq) (*Ack, error)
	DeleteAiDistort(context.Context, *DeleteAiDistortReq) (*Ack, error)
}

func RegisterAiServer(s *grpc.Server, srv AiServer) {
	s.RegisterService(&_Ai_serviceDesc, srv)
}

func _Ai_ShowAiDistort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShowReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).ShowAiDistort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Ai/ShowAiDistort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).ShowAiDistort(ctx, req.(*ShowReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_AddAiDistort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAiDistortReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).AddAiDistort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Ai/AddAiDistort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).AddAiDistort(ctx, req.(*AddAiDistortReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_DeleteAiDistort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAiDistortReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).DeleteAiDistort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Ai/DeleteAiDistort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).DeleteAiDistort(ctx, req.(*DeleteAiDistortReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ai_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Ai",
	HandlerType: (*AiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShowAiDistort",
			Handler:    _Ai_ShowAiDistort_Handler,
		},
		{
			MethodName: "AddAiDistort",
			Handler:    _Ai_AddAiDistort_Handler,
		},
		{
			MethodName: "DeleteAiDistort",
			Handler:    _Ai_DeleteAiDistort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai_service.proto",
}
